"""Rules Added

Revision ID: 20c349ddee71
Revises: 5c816dc34f75
Create Date: 2025-06-05 12:39:00.366615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20c349ddee71'
down_revision = '5c816dc34f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('brand_sorting', sa.Enum('NameAsc', 'NameDesc', 'RatingAsc', 'RatingDesc', name='brandsorting', create_type=False), nullable=False),
    sa.Column('product_sorting', sa.Enum('PriceAsc', 'PriceDesc', 'RatingAsc', 'RatingDesc', 'NameAsc', 'NameDesc', name='productsorting', create_type=False), nullable=False),
    sa.Column('spacing', sa.Float(), nullable=False),
    sa.Column('planogram_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['planogram_id'], ['planograms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planogram_id')
    )
    op.create_table('shelf_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_rules',
    sa.Column('share', sa.Float(), nullable=False),
    sa.Column('min_weight', sa.Float(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('shelf_rule_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shelf_rule_id'], ['shelf_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('products_category_brand_placement_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('category_brand_placement_id')

    op.drop_table('category_brand_placements')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=postgresql.ENUM('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN', 'NONE', name='ratingenum'),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('share')

    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('depth',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('max_weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.alter_column('max_weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('depth',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_brand_placement_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_category_brand_placement_id_fkey', 'category_brand_placements', ['category_brand_placement_id'], ['id'])
        batch_op.drop_column('category_id')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=postgresql.ENUM('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN', 'NONE', name='ratingenum'),
               nullable=False)

    op.create_table('category_brand_placements',
    sa.Column('share', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='category_brand_placements_brand_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='category_brand_placements_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='category_brand_placements_pkey')
    )
    op.drop_table('category_rules')
    op.drop_table('shelf_rules')
    op.drop_table('rules')
    
    op.execute('DROP TYPE IF EXISTS productsorting')
    op.execute('DROP TYPE IF EXISTS brandsorting')
    # ### end Alembic commands ###
