"""add_cat_brand_share_table

Revision ID: 26fd7587fb6b
Revises: cdcecb998097
Create Date: 2025-05-19 16:48:20.676571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fd7587fb6b'
down_revision = 'cdcecb998097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_brand_placements',
    sa.Column('share', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint('brands_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('share')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_brand_placement_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('products_brand_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category_brand_placements', ['category_brand_placement_id'], ['id'])
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_brand_id_fkey', 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('category_brand_placement_id')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('brands_category_id_fkey', 'categories', ['category_id'], ['id'])

    op.drop_table('category_brand_placements')
    # ### end Alembic commands ###
