"""empty message

Revision ID: 5c816dc34f75
Revises: 26fd7587fb6b
Create Date: 2025-05-19 17:37:39.597323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c816dc34f75'
down_revision = '26fd7587fb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_brand_placements', schema=None) as batch_op:
        batch_op.drop_constraint('category_brand_placements_brand_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_brand_placements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('category_brand_placements_brand_id_fkey', 'categories', ['brand_id'], ['id'])

    # ### end Alembic commands ###
