"""Rules Added 2

Revision ID: 76e134664260
Revises: 20c349ddee71
Create Date: 2025-06-05 13:33:47.599652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e134664260'
down_revision = '20c349ddee71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.alter_column('planogram_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.alter_column('planogram_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
